### PR TITLE
Editable and Minified Versions

### PR DESCRIPTION
**Pull request by MaXFalstein**
Editable and minified versions of all HTML, CSS and JS files have been
added. @PeterDaveHello feel free to change how gh-pages looks for files or leave it with the formatted HTML instead of the minified versions.
It is now easier to see what is going on in all of the files for editing and updating.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I'm not really understand what is this for, the result was generate by tools, and should always be minified, any reason you need the src?

**Comment by MaXFalstein** [comment]
If you want to play around with anything. I was using it to get more data out by hand for the time being.

**Comment by MaXFalstein** [comment]
I usually have my tools create minified index.min.html files.

**Comment by PeterDaveHello** [comment]
Sorry but I still not understand, what is the purpose here?

**Pull request closed without merging**
